# -*- coding: utf-8 -*-
"""alumnos_menu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11j_nlRPcSSBPLAg6CoBbmfjGAfuT3yb4
"""

datos ={
    "nombre" : input("ingresa nombre: "),
    "telefono" : input("ingrese telefono: "),
    "email" : input("ana@mail.cl: "),
    "edad": int(input("19"))
}
print("===MENU===")
print("[1] ver ficha")
print("[2] editar dato")
print("[3] salir")
opcion= int(input("ingrese una opcion"))


while True:
  if opcion ==1:
   print(datos)

  elif opcion ==2:
   edit=input("¿que desea editar de la ficha?")

   if edit== "nombre":
      cambio= input("nuevo nombre: ")
      datos["nombre"] = cambio

   elif edit== "telefono":
      cambio= input("nuevo telefono: ")
      datos["telefono"] = cambio

   elif edit == "email":
      cambio= input("nuevo email: ")
      datos["email"] = cambio

   elif edit == "edad":
      cambio= input("nuevo edad: ")
      datos["edad"] = cambio
  elif opcion ==3:
    print("saliendo del sistema...")
    break

  else:
    print("ingresa algo bien tonoto!!")
    break

