# -*- coding: utf-8 -*-
"""temperatura DEF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HDVr6tLzI_629fCQJ0mKUnNjWuXzyd9
"""

def temperatura_menu():
  print("[1] C° ->  F°")
  print("[2] F° ->  C°")
  print("[3] salir")
temperatura_menu()

def temperatura_menu():
  temp =float(input("ingrese la temperatura: "))
temperatura_menu()

def mostrar_resultado(orig, conv, ud):
   print(orig)
   print(conv)
   print(ud)
mostrar_resultado(3.0, 40, "CF")

c=float(input("ingrese temperatura: "))
def temp(c):
  return (c* 9/5)+32
temp(c)

f=float(input("ingrese temperatura: "))
def temp(f):
  return (f- 32)*5/9
temp(f)

